version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: mkdir -p build && cd build
      - run: g++ -o Source TestVsGit/Source.cpp -std=c++17
      - run: ./Source